Repository CS2113-AY1819S1-F10-3/main, pull requests merged in 2018-10, with the labels that each got.

#45 Added addSequenceDiagram and stored it in a folder
  docs/images/mainClassDiagram.png
  docs/images/mainClassDiagram1.png
  docs/images/sequenceDiagrams/addSequenceDiagram.png
  src/seedu/addressbook/ui/MainWindow.java
Labels: priority.medium, type.task

#48 Read Notification Class - Tested and working
  notifications.txt
  src/seedu/addressbook/inbox/Inbox.java
  src/seedu/addressbook/inbox/Msg.java
  src/seedu/addressbook/inbox/ReadNotification.java
  src/seedu/addressbook/inbox/WriteNotification.java
Labels: priority.high, status.ongoing

#86 Renamed profile pictures to Github usernames
  docs/images/ShreyasKp.png
  docs/images/andyrobert3.png
  docs/images/iamputradanish.png
  docs/images/muhdharun.png
  docs/images/ongweekeong.png
  docs/images/profiles/Putra.png
Labels: priority.high, severity.Low

#90 Trivial UI features, Added comments & removed deprecated API call
  .gitignore
  src/seedu/addressbook/Location.java
  src/seedu/addressbook/Main.java
  src/seedu/addressbook/commands/EditCommand.java
  src/seedu/addressbook/common/HttpRestClient.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/storage/StorageFile.java
  src/seedu/addressbook/ui/MainWindow.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.high

#94 New Msg class constructors created.
  notifications.txt
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/inbox/Inbox.java
  src/seedu/addressbook/inbox/Msg.java
  src/seedu/addressbook/inbox/WriteNotification.java
Labels: priority.medium

#98 Implement update password feature
  addressbook.txt
  docs/images/ShreyasKp.png
  passwordStorage.txt
  src/passwordUpdater.java
  src/seedu/addressbook/commands/HelpCommand.java
  src/seedu/addressbook/commands/UpdatePasswordCommand.java
  src/seedu/addressbook/ui/MainWindow.java
Labels: priority.high, type.epic

#99 Add prediction feature for commands
  src/seedu/addressbook/autocorrect/Dictionary.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/ui/MainWindow.java
  tempfile.txt
Labels: priority.high, type.epic

#110 Messages now appear with the correct ordering.
  .gitignore
  notifications.txt
  src/seedu/addressbook/inbox/Inbox.java
  src/seedu/addressbook/inbox/Msg.java
  src/seedu/addressbook/inbox/ReadNotification.java
  src/seedu/addressbook/inbox/WriteNotification.java
Labels: priority.high, status.ongoing

#111 Update Developer Guide
  docs/DeveloperGuide.adoc
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/ui/MainWindow.java
Labels: type.task

#113 Updated DG - added use case for loading and replying messages
  docs/DeveloperGuide.adoc
Labels: type.task

#108 Add screening history feature and add codecov
  .travis.yml
  ScreeningHistory.txt
  build.gradle
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  parserLog.log.1
  src/seedu/addressbook/commands/CheckCommand.java
  src/seedu/addressbook/commands/Command.java
  src/seedu/addressbook/commands/DeleteCommand.java
  src/seedu/addressbook/commands/FindCommand.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/data/AddressBook.java
  src/seedu/addressbook/data/person/NRIC.java
  src/seedu/addressbook/data/person/Person.java
  src/seedu/addressbook/data/person/ReadOnlyPerson.java
  src/seedu/addressbook/data/person/UniquePersonList.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/storage/jaxb/AdaptedAddressBook.java
  src/seedu/addressbook/storage/jaxb/AdaptedPerson.java
  src/seedu/addressbook/ui/Formatter.java
  src/seedu/addressbook/ui/MainWindow.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.high, type.epic, type.task

#115 Added Edit Command, Developer Guide, Refactored Location with Offense Class & added Request Command with limited cases
  .gitignore
  addressbook.txt
  docs/DeveloperGuide.adoc
  src/seedu/addressbook/Location.java
  src/seedu/addressbook/autocorrect/Dictionary.java
  src/seedu/addressbook/commands/AddCommand.java
  src/seedu/addressbook/commands/Command.java
  src/seedu/addressbook/commands/DeleteCommand.java
  src/seedu/addressbook/commands/EditCommand.java
  src/seedu/addressbook/commands/FindCommand.java
  src/seedu/addressbook/commands/RequestHelp.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/data/person/Offense.java
  src/seedu/addressbook/data/person/Person.java
  src/seedu/addressbook/data/person/ReadOnlyPerson.java
  src/seedu/addressbook/inbox/Msg.java
  src/seedu/addressbook/inbox/NotificationManager.java
  src/seedu/addressbook/logic/Logic.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/storage/jaxb/AdaptedPerson.java
  src/seedu/addressbook/storage/jaxb/AdaptedTag.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.medium

#116 edited User Guide and Developer Guide
  ScreeningHistory.txt
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/seedu/addressbook/commands/CheckCommand.java
  src/seedu/addressbook/commands/FindCommand.java
  src/seedu/addressbook/data/person/Person.java
Labels: priority.high

#117 Fixed Edit Command
  src/seedu/addressbook/commands/Command.java
  src/seedu/addressbook/commands/EditCommand.java
  src/seedu/addressbook/commands/FindCommand.java
  src/seedu/addressbook/data/AddressBook.java
  src/seedu/addressbook/data/person/Offense.java
  src/seedu/addressbook/data/person/Person.java
  src/seedu/addressbook/data/person/ReadOnlyPerson.java
  src/seedu/addressbook/data/person/UniquePersonList.java
  src/seedu/addressbook/storage/jaxb/AdaptedPerson.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.high, type.bug

#120 Standardized formatting for DG
  docs/DeveloperGuide.adoc
  src/seedu/addressbook/inbox/Msg.java
  src/seedu/addressbook/parser/Parser.java
Labels: type.task

#123 Update Password Feature
  .gitignore
  ScreeningHistory.txt
  desktop.ini
  docs/images/andyrobert31.png
  docs/images/iamputradanish1.png
  docs/images/muhdharun1.png
  docs/images/ongweekeong1.png
  docs/images/shreyaskp1.png
  parserLog.log.1
  passwordStorage.txt
  src/seedu/addressbook/commands/HelpCommand.java
  src/seedu/addressbook/commands/LockCommand.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/password/Password.java
  src/seedu/addressbook/readandwrite/ReaderAndWriter.java
  src/seedu/addressbook/timeanddate/TimeAndDate.java
  src/seedu/addressbook/ui/MainWindow.java
  tempfile.txt
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.high, type.epic

#126 Update finer details of Developer Guide
  docs/DeveloperGuide.adoc
Labels: priority.high, type.task

#125 Added test cases for Check and Person classes
  ScreeningHistory.txt
  src/seedu/addressbook/autocorrect/Dictionary.java
  src/seedu/addressbook/commands/Command.java
  src/seedu/addressbook/data/person/Person.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/ui/MainWindow.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.high

#127 Add invalid command output format for autocorrect feature
  .gitignore
  ScreeningHistory.txt
  passwordStorage.txt
  src/seedu/addressbook/autocorrect/Dictionary.java
  src/seedu/addressbook/ui/MainWindow.java
Labels: priority.high, type.epic

#128 Edited DG
  docs/DeveloperGuide.adoc
  src/seedu/addressbook/commands/HelpCommand.java
Labels: priority.high

#131 Update Developer Guide Implementation of Autocorrection feature
  docs/DeveloperGuide.adoc
Labels: type.task

#135 Fixed empty list edit command bug
  env
  src/seedu/addressbook/commands/EditCommand.java
  src/seedu/addressbook/common/Messages.java
Labels: type.bug

#139 Fixed PO invalid command bug
  src/seedu/addressbook/password/Password.java
Labels: priority.high, severity.High, type.bug

#142 InboxCommand bugs fixed. Fully functional.
  notifications.txt
  src/seedu/addressbook/Location.java
  src/seedu/addressbook/commands/HelpCommand.java
  src/seedu/addressbook/commands/InboxCommand.java
  src/seedu/addressbook/commands/RequestHelp.java
  src/seedu/addressbook/inbox/Inbox.java
  src/seedu/addressbook/inbox/MessageFilePaths.java
  src/seedu/addressbook/inbox/Msg.java
  src/seedu/addressbook/inbox/ReadNotification.java
  src/seedu/addressbook/inbox/WriteNotification.java
  src/seedu/addressbook/timeanddate/TimeAndDate.java
  src/seedu/addressbook/ui/MainWindow.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.high

#141 Add Putra Project portfolio draft 1 and test cases
  docs/images/andyrobert31.png
  docs/images/iamputradanish1.png
  docs/images/muhdharun1.png
  docs/images/ongweekeong1.png
  docs/images/shreyaskp1.png
  docs/projectPortfolio/putraProjectPortfolio.adoc
  src/seedu/addressbook/commands/HelpCommand.java
  src/seedu/addressbook/commands/LockCommand.java
  src/seedu/addressbook/commands/UpdatePasswordCommand.java
  src/seedu/addressbook/password/Password.java
  src/seedu/addressbook/readandwrite/ReaderAndWriter.java
  src/seedu/addressbook/timeanddate/TimeAndDate.java
  src/seedu/addressbook/ui/MainWindow.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.high, type.task

#140 Reformatted UG
  ScreeningHistory.txt
  docs/UserGuide.adoc
  docs/images/AddCommand.png
  docs/images/CheckCommand.png
  docs/images/HelpCommand.png
  docs/images/ListCommand.png
  passwordStorage.txt
  src/seedu/addressbook/autocorrect/Dictionary.java
  src/seedu/addressbook/commands/AddCommand.java
  src/seedu/addressbook/commands/CheckCommand.java
  src/seedu/addressbook/commands/Command.java
  src/seedu/addressbook/commands/DatetimeCommand.java
  src/seedu/addressbook/commands/FindCommand.java
  src/seedu/addressbook/commands/HelpCommand.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/data/AddressBook.java
  src/seedu/addressbook/data/person/ReadOnlyPerson.java
  src/seedu/addressbook/data/person/Status.java
  src/seedu/addressbook/timeanddate/TimeAndDate.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.high, type.enhancement

#143 Created class to store message storage filepaths.
  src/seedu/addressbook/inbox/Inbox.java
  src/seedu/addressbook/inbox/MessageFilePaths.java
  src/seedu/addressbook/inbox/WriteNotification.java
Labels: priority.medium

#144 Change ID names
  ScreeningHistory.txt
  src/seedu/addressbook/commands/HelpCommand.java
  src/seedu/addressbook/commands/UpdatePasswordCommand.java
  src/seedu/addressbook/password/Password.java
  src/seedu/addressbook/ui/MainWindow.java
Labels: priority.high, type.task

#148 Extended autocorrection feature and added author tag, date and time command along with tests
  ScreeningHistory.txt
  src/seedu/addressbook/autocorrect/CheckDistance.java
  src/seedu/addressbook/autocorrect/Dictionary.java
  src/seedu/addressbook/autocorrect/EditDistance.java
  src/seedu/addressbook/commands/DateTimeCommand.java
  src/seedu/addressbook/commands/DatetimeCommand.java
  src/seedu/addressbook/commands/DeleteCommand.java
  src/seedu/addressbook/commands/Dictionary.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/ui/MainWindow.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.high, status.ongoing, type.epic, type.task

#149 ReadCommand Class added and fully integrated.
  notifications.txt
  src/seedu/addressbook/commands/Dictionary.java
  src/seedu/addressbook/commands/HelpCommand.java
  src/seedu/addressbook/commands/InboxCommand.java
  src/seedu/addressbook/commands/ReadCommand.java
  src/seedu/addressbook/inbox/Inbox.java
  src/seedu/addressbook/inbox/MessageFilePaths.java
  src/seedu/addressbook/inbox/Msg.java
  src/seedu/addressbook/inbox/ReadNotification.java
  src/seedu/addressbook/inbox/WriteNotification.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/password/Password.java
  src/seedu/addressbook/timeanddate/TimeAndDate.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.high, type.enhancement

#150 New commands, collate annotations, updated UG
  ScreeningHistory.txt
  docs/UserGuide.adoc
  parserLog.log.1
  src/seedu/addressbook/PatrolResourceStatus.java
  src/seedu/addressbook/commands/AddCommand.java
  src/seedu/addressbook/commands/CheckCommand.java
  src/seedu/addressbook/commands/CheckPOStatusCommand.java
  src/seedu/addressbook/commands/Command.java
  src/seedu/addressbook/commands/DeleteCommand.java
  src/seedu/addressbook/commands/Dictionary.java
  src/seedu/addressbook/commands/FindCommand.java
  src/seedu/addressbook/commands/HelpCommand.java
  src/seedu/addressbook/commands/UpdateStatusCommand.java
  src/seedu/addressbook/data/AddressBook.java
  src/seedu/addressbook/data/PoliceOfficers/Case.java
  src/seedu/addressbook/data/PoliceOfficers/PatrolID.java
  src/seedu/addressbook/data/PoliceOfficers/PatrolResource.java
  src/seedu/addressbook/data/PoliceOfficers/Personnel.java
  src/seedu/addressbook/data/PoliceOfficers/ReadOnlyPatrolResource.java
  src/seedu/addressbook/data/PoliceOfficers/State.java
  src/seedu/addressbook/data/person/DateOfBirth.java
  src/seedu/addressbook/data/person/NRIC.java
  src/seedu/addressbook/data/person/Offense.java
  src/seedu/addressbook/data/person/Person.java
  src/seedu/addressbook/data/person/PostalCode.java
  src/seedu/addressbook/data/person/ReadOnlyPerson.java
  src/seedu/addressbook/data/person/Status.java
  src/seedu/addressbook/data/person/UniquePersonList.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/ui/Formatter.java
  src/seedu/addressbook/ui/MainWindow.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.high

#152 Added Edit Command test cases with Error checking for Edit Command
  build.gradle
  src/seedu/addressbook/commands/Dictionary.java
  src/seedu/addressbook/commands/DispatchBackup.java
  src/seedu/addressbook/commands/EditCommand.java
  src/seedu/addressbook/commands/RequestHelp.java
  src/seedu/addressbook/commands/RequestHelpCommand.java
  src/seedu/addressbook/ui/MainWindow.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.medium, type.bug

#155 Added Test Cases & Updated Collate for Test Cases
  build.gradle
  collated/test/ShreyasKp.md
  collated/test/andyrobert3.md
  collated/test/muhdharun.md
  collated/test/ongweekeong.md
  src/seedu/addressbook/commands/InboxCommand.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/inbox/Msg.java
  src/seedu/addressbook/inbox/WriteNotification.java
  src/seedu/addressbook/timeanddate/TimeAndDate.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.high, status.ongoing, type.task

#156 Test cases added
  META-INF/MANIFEST.MF
  ScreeningHistory.txt
  build.gradle
  notifications.txt
  parserLog.log.1
  src/META-INF/MANIFEST.MF
  src/seedu/addressbook/PatrolResourceStatus.java
  src/seedu/addressbook/commands/CheckPOStatusCommand.java
  src/seedu/addressbook/commands/UpdateStatusCommand.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/data/person/Status.java
  src/seedu/addressbook/parser/Parser.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.high

#161 Edit offense class
  ScreeningHistory.txt
  inboxMessages/headquartersInbox
  notifications.txt
  offencesorted.txt
  parserLog.log.1
  src/seedu/addressbook/commands/AddCommand.java
  src/seedu/addressbook/commands/CheckCommand.java
  src/seedu/addressbook/commands/CheckPOStatusCommand.java
  src/seedu/addressbook/commands/Command.java
  src/seedu/addressbook/commands/DateTimeCommand.java
  src/seedu/addressbook/commands/DeleteCommand.java
  src/seedu/addressbook/commands/FindCommand.java
  src/seedu/addressbook/commands/UpdateStatusCommand.java
  src/seedu/addressbook/data/person/DateOfBirth.java
  src/seedu/addressbook/data/person/Offense.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.high
