Repository CS2113-AY1819S1-F10-3/main, pull requests merged in 2018-11, with the labels that each got.

#164 Added Test Cases for Msg class and MessageFilePaths class.
  _reposense/config.json
  docs/Ong Wee Keong_Project Portfolio.adoc
  src/seedu/addressbook/inbox/Inbox.java
  src/seedu/addressbook/inbox/Msg.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.medium, type.task

#167 Added method to clear all inboxes in WriteNotification class.
  docs/Ong Wee Keong_Project Portfolio.adoc
  src/seedu/addressbook/commands/DispatchCommand.java
  src/seedu/addressbook/inbox/WriteNotification.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/storage/StorageFileTest.java
Labels: priority.medium

#171 Added ClearInboxCommand Class
  .gitignore
  notifications.txt
  src/seedu/addressbook/Main.java
  src/seedu/addressbook/commands/ClearInboxCommand.java
  src/seedu/addressbook/commands/Dictionary.java
  src/seedu/addressbook/commands/InboxCommand.java
  src/seedu/addressbook/commands/ReadCommand.java
  src/seedu/addressbook/inbox/Inbox.java
  src/seedu/addressbook/inbox/Msg.java
  src/seedu/addressbook/inbox/ReadNotification.java
  src/seedu/addressbook/inbox/WriteNotification.java
  src/seedu/addressbook/parser/Parser.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.medium

#172 Add Project Portfolio Draft, refactor AutoCorrect and add test for add command.
  ScreeningHistory.txt
  docs/projectPortfolio/shreyasProjectPortfolio.adoc
  inboxMessages/headquartersInbox
  notifications.txt
  src/seedu/addressbook/autocorrect/AutoCorrect.java
  src/seedu/addressbook/commands/Dictionary.java
  src/seedu/addressbook/ui/MainWindow.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.high, status.ongoing, type.epic

#169 Added IOException test case
  ScreeningHistory.txt
  inboxMessages/headquartersInbox
  src/seedu/addressbook/commands/FindCommand.java
  src/seedu/addressbook/data/AddressBook.java
  src/seedu/addressbook/data/person/Person.java
  src/seedu/addressbook/timeanddate/TimeAndDate.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.high

#173 Add application icon
  ScreeningHistory.txt
  docs/images/Icon PRISM.png
  inboxMessages/headquartersInbox
  src/seedu/addressbook/autocorrect/AutoCorrect.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.medium, type.task

#170 Added Dispatch Command Test Cases and changed success messages
  docs/projectPortfolio/johndoe.adoc
  src/seedu/addressbook/PatrolResourceStatus.java
  src/seedu/addressbook/commands/CommandResult.java
  src/seedu/addressbook/commands/DispatchCommand.java
  src/seedu/addressbook/commands/RequestHelpCommand.java
  src/seedu/addressbook/common/Location.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/inbox/MessageFilePaths.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.high, severity.Medium

#168 Changed UI
  parserLog.log.1
  src/seedu/addressbook/Main.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/password/Password.java
  src/seedu/addressbook/timeanddate/TimeAndDate.java
  src/seedu/addressbook/ui/DarkTheme.css
  src/seedu/addressbook/ui/Gui.java
  src/seedu/addressbook/ui/MainWindow.java
  src/seedu/addressbook/ui/mainwindow.fxml
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.medium, type.task

#175 Reverse getID()
  src/seedu/addressbook/password/Password.java
  src/seedu/addressbook/ui/mainwindow.fxml
Labels: priority.high, severity.High

#176 Fix AutoCorrect bug for displaying Invalid command, and update User Guide
  ScreeningHistory.txt
  docs/UserGuide.adoc
  inboxMessages/PO3
  inboxMessages/PO4
  inboxMessages/headquartersInbox
  notifications.txt
  src/seedu/addressbook/ui/MainWindow.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.high, type.bug

#177 Included 'clearinbox' command into UG
  docs/UserGuide.adoc
Labels: priority.medium

#178 Minor edit to lock screen
  src/seedu/addressbook/commands/LockCommand.java
Labels: priority.medium

#184 Initialize text files upon start up
  OffenceList.txt
  PropertyStorage.txt
  ScreeningHistory.txt
  docs/projectPortfolio/matthewProjectPortfolio.pdf
  env
  inboxMessages/PO3
  inboxMessages/PO4
  inboxMessages/headquartersInbox
  passwordStorage.txt
  src/seedu/addressbook/Main.java
  src/seedu/addressbook/commands/LockCommand.java
  src/seedu/addressbook/data/AddressBook.java
  src/seedu/addressbook/ui/MainWindow.java
  src/seedu/addressbook/ui/mainwindow.fxml
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.high, severity.High

#214 Changed Edit Command to support optional parameters
  src/seedu/addressbook/commands/AddCommand.java
  src/seedu/addressbook/commands/DispatchCommand.java
  src/seedu/addressbook/commands/EditCommand.java
  src/seedu/addressbook/commands/RequestHelpCommand.java
  src/seedu/addressbook/common/Location.java
  src/seedu/addressbook/logic/Logic.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/password/Password.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.medium

#215 edited dispatch command in UG
  docs/UserGuide.adoc
Labels: priority.medium

#216 Refactor Lock and Exit command to Logout and Shutdown
  parserLog.log
  passwordStorage.txt
  src/seedu/addressbook/autocorrect/AutoCorrect.java
  src/seedu/addressbook/commands/Dictionary.java
  src/seedu/addressbook/commands/HelpCommand.java
  src/seedu/addressbook/commands/LogoutCommand.java
  src/seedu/addressbook/commands/ShutdownCommand.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/password/Password.java
  src/seedu/addressbook/ui/DarkTheme.css
  src/seedu/addressbook/ui/MainWindow.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.medium

#223 Added new test cases
  TestScreen.txt
  docs/UserGuide.adoc
  inboxMessages/PO3
  inboxMessages/PO4
  inboxMessages/headquartersInbox
  parserLog.log
  src/seedu/addressbook/commands/CheckCommand.java
  src/seedu/addressbook/commands/FindCommand.java
  src/seedu/addressbook/common/Messages.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.high

#219 Added InboxCommand, Fixed bugs from PE and changed output time format for ShowUnread.
  .gitignore
  src/seedu/addressbook/autocorrect/AutoCorrect.java
  src/seedu/addressbook/commands/Dictionary.java
  src/seedu/addressbook/commands/HelpCommand.java
  src/seedu/addressbook/commands/InboxCommand.java
  src/seedu/addressbook/commands/ReadCommand.java
  src/seedu/addressbook/commands/ShowUnreadCommand.java
  src/seedu/addressbook/inbox/Msg.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/timeanddate/TimeAndDate.java
  test/java/seedu/addressbook/common/UtilsTest.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.medium, severity.Low, type.enhancement

#218 Added tests for Edit Command and improved Edit Command error handling
  src/seedu/addressbook/commands/Command.java
  src/seedu/addressbook/commands/DispatchCommand.java
  src/seedu/addressbook/commands/EditCommand.java
  src/seedu/addressbook/data/person/Offense.java
  src/seedu/addressbook/parser/Parser.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.medium, severity.Medium

#221 add more test cases to Password class
  .gitignore
  collated/functional/muhdharun.md
  docs/DeveloperGuide.adoc
  src/seedu/addressbook/Main.java
  src/seedu/addressbook/commands/AddCommand.java
  src/seedu/addressbook/commands/CheckCommand.java
  src/seedu/addressbook/commands/FindCommand.java
  src/seedu/addressbook/data/tag/Tag.java
  src/seedu/addressbook/logic/Logic.java
  src/seedu/addressbook/password/Password.java
  src/seedu/addressbook/readandwrite/ReaderAndWriter.java
  src/seedu/addressbook/storage/jaxb/AdaptedPerson.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.high

#224 Edited UI to work offline. Added spf icon
  docs/images/IconPRISM.png
  docs/images/SPF.png
  src/seedu/addressbook/ui/DarkTheme.css
  src/seedu/addressbook/ui/Gui.java
Labels: priority.low, type.task

#229 Fixed logout bug
  src/seedu/addressbook/commands/InboxCommand.java
  src/seedu/addressbook/commands/LogoutCommand.java
  src/seedu/addressbook/inbox/Inbox.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: bug.functionality, priority.high

#230 Populated police records with 20 contacts
  build.gradle
  src/resources/PrismBackground.png
  src/resources/SPF.png
  src/seedu/addressbook/storage/StorageFile.java
  src/seedu/addressbook/ui/DarkTheme.css
  src/seedu/addressbook/ui/Gui.java
Labels: priority.high, type.task

#231 sorted project portfolio
  docs/ongweekeong.adoc
  docs/projectPortfolio/johndoe.adoc
  docs/team/andyrobert3.adoc
  docs/team/iamputradanish.adoc
  docs/team/shreyaskp.adoc
Labels: priority.high, type.task

#233 Changed directory references and moved PPP to team folder
  docs/team/ongweekeong.adoc
Labels: priority.high, type.task

#236 Edited Developer Guide with UML Sequence Diagrams
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/CheckCommand_Sequence.png
  docs/images/DeleteCommand_Sequence.png
  docs/images/DispatchCommand.PNG
  docs/images/EditCommand.PNG
  docs/images/FindCommand_Sequence.png
  docs/images/RequestCommand.PNG
  docs/images/inboxCommand.PNG
  docs/team/andyrobert3.adoc
  src/seedu/addressbook/PatrolResourceStatus.java
  src/seedu/addressbook/commands/DispatchCommand.java
  src/seedu/addressbook/commands/RequestHelpCommand.java
  src/seedu/addressbook/data/person/Offense.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.medium

#238 Fix Autocorrection bug, refactor code and add instructions on using Checkstyle
  docs/UsingCheckstyle.adoc
  docs/images/checkstyle-idea-configuration.png
  docs/images/checkstyle-idea-scan-scope.png
  src/seedu/addressbook/autocorrect/AutoCorrect.java
  src/seedu/addressbook/autocorrect/CheckDistance.java
  src/seedu/addressbook/autocorrect/EditDistance.java
  src/seedu/addressbook/commands/CheckCommand.java
  src/seedu/addressbook/commands/Command.java
  src/seedu/addressbook/commands/DeleteCommand.java
  src/seedu/addressbook/commands/Dictionary.java
  src/seedu/addressbook/commands/EditCommand.java
  src/seedu/addressbook/ui/MainWindow.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: bug.functionality, priority.high, type.epic

#239 Make password class static
  docs/team/iamputradanish.adoc
  src/seedu/addressbook/commands/LogoutCommand.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/password/Password.java
  src/seedu/addressbook/ui/MainWindow.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.low

#237 Updated DG - Full main class diagram
  docs/DeveloperGuide.adoc
  docs/Diagrams.pptx
  docs/UserGuide.adoc
  docs/images/mainClassDiagramFULL.png
  docs/images/mainClassDiagramFULLedited.png
  docs/images/mainClassDiagramUpdated.png
  docs/team/ongweekeong.adoc
  src/seedu/addressbook/commands/ClearInboxCommand.java
  src/seedu/addressbook/commands/InboxCommand.java
  src/seedu/addressbook/commands/ReadCommand.java
  src/seedu/addressbook/commands/ShowUnreadCommand.java
  src/seedu/addressbook/parser/Parser.java
Labels: priority.high, type.task

#241 Edited test cases to align with Checkstyle requirements
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.high, severity.Low, type.task

#242 Add checkstyle for Test code and update documentation
  .travis.yml
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/UsingTravis.adoc
  docs/images/AutoCorrectSequence.png
  docs/images/build_pending.png
  docs/images/flick_repository_switch.png
  docs/images/generate_token.png
  docs/images/grant_access.png
  docs/images/request_access.png
  docs/images/review_and_add.png
  docs/images/signing_in.png
  docs/images/travis_add_token.png
  docs/images/travis_build.png
  docs/team/andyrobert3.adoc
  docs/team/shreyaskp.adoc
  src/seedu/addressbook/autocorrect/CheckDistance.java
  src/seedu/addressbook/commands/DateTimeCommand.java
  src/seedu/addressbook/ui/MainWindow.java
Labels: priority.high, type.epic

#243 Added Harun PPP, fixed Edit Command Bug, Refactored code for checkstyle, UML Sequence Diagrams
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AutoCorrect.png
  docs/images/CheckStatus_Sequence.png
  docs/images/Password.PNG
  docs/images/UpdateStatus_Sequence.png
  docs/images/unlockDevice.png
  docs/images/updatePassword.png
  docs/team/andyrobert3.adoc
  docs/team/muhdharun.adoc
  src/seedu/addressbook/PatrolResourceStatus.java
  src/seedu/addressbook/commands/DispatchCommand.java
  src/seedu/addressbook/commands/EditCommand.java
  src/seedu/addressbook/commands/RequestHelpCommand.java
  src/seedu/addressbook/common/HttpRestClient.java
  src/seedu/addressbook/common/Location.java
  src/seedu/addressbook/data/exception/PatrolResourceUnavailableException.java
  src/seedu/addressbook/data/person/Offense.java
  src/seedu/addressbook/parser/Parser.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.high

#244 Main Class Diagram Corrected
  docs/DeveloperGuide.adoc
  docs/Diagrams.pptx
  docs/images/mainClassDiagramFULLedited.png
  docs/team/ongweekeong.adoc
Labels: priority.high, type.task

#245 update developer guide
  docs/DeveloperGuide.adoc
  docs/team/iamputradanish.adoc
  screeningHistory.txt
  src/seedu/addressbook/commands/LogoutCommand.java
  src/seedu/addressbook/data/AddressBook.java
  src/seedu/addressbook/logic/Logic.java
  src/seedu/addressbook/password/Password.java
  src/seedu/addressbook/ui/MainWindow.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.high, type.task

#247 Updated DG and added test cases
  docs/DeveloperGuide.adoc
  inboxMessages/PO3
  inboxMessages/PO4
  inboxMessages/headquartersInbox
  src/seedu/addressbook/commands/AddCommand.java
  src/seedu/addressbook/commands/CheckCommand.java
  src/seedu/addressbook/commands/CheckPoStatusCommand.java
  src/seedu/addressbook/commands/Command.java
  src/seedu/addressbook/commands/DateTimeCommand.java
  src/seedu/addressbook/commands/DeleteCommand.java
  src/seedu/addressbook/commands/EditCommand.java
  src/seedu/addressbook/commands/FindCommand.java
  src/seedu/addressbook/data/person/DateOfBirth.java
  src/seedu/addressbook/data/person/UniquePersonList.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/timeanddate/TimeAndDate.java
  src/seedu/addressbook/ui/Gui.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
  testScreen.txt
Labels: priority.high, type.epic

#246 update ug
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/iamputradanish.adoc
  src/seedu/addressbook/readandwrite/ReaderAndWriter.java
  src/seedu/addressbook/storage/StorageFile.java
  src/seedu/addressbook/timeanddate/TimeAndDate.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/storage/StorageFileTest.java
Labels: priority.high, type.task

#248 Added Developer Guide with UML Sequence Diagrams
  README.adoc
  collated/functional/andyrobert3.md
  collated/functional/muhdharun.md
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AutoCorrect.png
  docs/images/ClearInboxCommand_Sequence.png
  docs/images/ReadCommand_Sequence.png
  docs/images/UpdateStatus_Sequence.png
  docs/team/andyrobert3.adoc
  docs/team/muhdharun.adoc
  src/seedu/addressbook/commands/CheckPoStatusCommand.java
  src/seedu/addressbook/commands/DispatchCommand.java
  src/seedu/addressbook/commands/ReadCommand.java
  src/seedu/addressbook/commands/RequestHelpCommand.java
  src/seedu/addressbook/commands/UpdateStatusCommand.java
  src/seedu/addressbook/common/PatrolResourceStatus.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/password/Password.java
  test/java/seedu/addressbook/logic/LogicTest.java
  testScreen.txt
Labels: priority.high

#249 Update DG and PPP
  docs/DeveloperGuide.adoc
  docs/team/shreyaskp.adoc
  src/seedu/addressbook/autocorrect/AutoCorrect.java
  src/seedu/addressbook/autocorrect/CheckDistance.java
  src/seedu/addressbook/commands/Dictionary.java
Labels: priority.high, type.task
