Repository CS2113-AY1819S1-F10-3/main, pull requests merged in 2018-09, with the labels that each got.

#23 Added one-password feature
  src/seedu/addressbook/commands/LockCommand.java
  src/seedu/addressbook/commands/PasswordCommand.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/ui/MainWindow.java
Labels: priority.high, type.epic

#22 Made HttpClient Class & Location Class
  build.gradle
  src/seedu/addressbook/Location.java
  src/seedu/addressbook/common/HttpRestClient.java
Labels: priority.medium

#24 Message Class
  notifications.txt
  src/seedu/addressbook/inbox/Inbox.java
  src/seedu/addressbook/inbox/Msg.java
  src/seedu/addressbook/inbox/NotificationManager.java
  src/seedu/addressbook/inbox/ReadNotification.java
  src/seedu/addressbook/inbox/WriteNotification.java
  src/seedu/addressbook/storage/StorageFile.java
Labels: priority.high

#26 Delete by Name & Index feature, solved CS2113T Bug of deleting before listing
  src/seedu/addressbook/commands/Command.java
  src/seedu/addressbook/commands/DeleteCommand.java
  src/seedu/addressbook/common/Utils.java
  src/seedu/addressbook/parser/Parser.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.high

#25 Added accessibility through password feature.
  src/seedu/addressbook/commands/HQPPasswordCommand.java
  src/seedu/addressbook/commands/HelpCommand.java
  src/seedu/addressbook/commands/LockCommand.java
  src/seedu/addressbook/commands/POPasswordCommand.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/ui/MainWindow.java
Labels: priority.high

#34 add EditDistance algorithm and Dictionary
  src/seedu/addressbook/autocorrect/Dictionary.java
  src/seedu/addressbook/autocorrect/EditDistance.java
Labels: priority.high

#33 Add edit command feature with tests
  src/seedu/addressbook/Location.java
  src/seedu/addressbook/commands/Command.java
  src/seedu/addressbook/commands/DeleteCommand.java
  src/seedu/addressbook/commands/EditCommand.java
  src/seedu/addressbook/commands/HelpCommand.java
  src/seedu/addressbook/data/AddressBook.java
  src/seedu/addressbook/parser/Parser.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.medium
